### ISSUE TITLE
Towards 2.4

### ISSUE THREAD

**Issue by DiamonDinoia** [flatironinstitute/finufft#491]
Possible future tasks for 2.4

Based on future discussions this can be deferred anytime. Grouping for simplicity:
- [x] De-Macroize #482 #483 
- [x] Type 3 on GPU #489
- [x] Cufinufft windows compile #604  
- [x] Update dependencies #621 
- [x] Remove alloca #570 
- [x] Spreadinterponly (CPU and GPU) #602
- [x] GPU math test for spreadinterponly.  #624 
- [x] remove cmake-presets #625
- [x] Tune choice of 1.25 over 2.00 in the plan when upsampfac=0.0 is chosen (Marco will make PR)
- [x] Matlab cuFINUFFT support #432 
- [x] decide Cuda 11.4 or 12.x for python wheels... ask users on Discussion?
